AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Demonstrate a basic fact skill built with the ASK NodeJS SDK
Resources:
  CodecademyFlashcards2:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: .
      Description: Demonstrate a basic fact skill built with the ASK NodeJS SDK
      MemorySize: 128
      Timeout: 7
      Role: 'arn:aws:iam::125042910629:role/lambda_dynamodb_fullaccess'
      Events:
        AlexaSkillEvent:
          Type: AlexaSkill
      Tags:
        'lambda-console:blueprint': alexa-skill-kit-sdk-factskill
